framework:
    asset_mapper:
        paths:
            - assets/
        missing_import_mode: strict

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn  # ✅ dégradé tolérant en prod
            javascript_importmap:
                preloads: true        # ✅ ES module <link rel="modulepreload">
                polyfill: false       # ou true si tu supportes d'anciens navigateurs
            compiler:
                minify: true          # ✅ minification JS/CSS
                source_maps: false    # ✅ pas de sourcemap inutile en prod
                transpile: false      # true si tu as des .ts ou JS moderne non supporté
