version: "3.8"

services:
  app:
    build: .
    container_name: steam-status-app
    ports:
      - "${PORT:-8080}:8080"
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      STEAM_API_KEY: "${STEAM_API_KEY}"
    volumes:
      - .:/var/www/html
