name: Build and Push Docker Image

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: valpxl
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: valpxl/steam-status:latest

      - name: Update Docker Hub README
        uses: peter-evans/dockerhub-description@v3
        with:
          username: valpxl
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: valpxl/steam-status
          readme-filepath: ./README.en.md
